/**
 * Generated by tsnapi — public API snapshot of `aiex-cli` */
// Interfaces
export interface DoctorDiagnostics {
  cli: {
    name: string;
    version: string;
    executable: string;
  };
  runtime: {
    node: string;
    platform: string;
    arch: string;
    shell: string;
    packageManager: string;
  };
  system: {
    os: string;
    cwd: string;
  };
  imageOcr: {
    platformSupported: boolean;
    dependencyLoaded: boolean;
    ocrOk: boolean | null;
    imagePath?: string;
    recognizedText?: string;
    confidence?: number;
    error?: string;
  };
  config: {
    path: string;
    keys: string[];
  };
  project: {
    aiexDir: string;
    dirExists: boolean;
    schemaCount: number;
    schemaFiles: string[];
    aiConfig: boolean;
    aiApiKeySet: boolean;
    aiModelCount: number;
    aiModels: string[];
    aiVisionModelCount: number;
    aiStructuredOutputModelCount: number;
    aiProvider: string | null;
    aiConnectionOk: boolean | null;
    pdfConverter: string | null;
    pdfConverterOk: boolean | null;
    pdfConverterError?: string;
    hasDatabase: boolean;
    databaseTablesOk: boolean | null;
    missingDatabaseTables: string[];
    migrationCount: number;
    schemaValidCount: number;
    invalidSchemas: Array<{
      file: string;
      error: string;
    }>;
    errors: string[];
  };
}
export interface JsonSchemaProperty {
  description?: string;
  type: 'string' | 'integer' | 'number' | 'boolean' | 'object' | 'array' | 'null';
  format?: string;
  pattern?: string;
  enum?: (string | number)[];
  primary?: boolean;
  autoIncrement?: boolean;
  unique?: boolean;
  default?: unknown;
  maxLength?: number;
  minLength?: number;
  minimum?: number;
  maximum?: number;
  examples?: unknown[];
  xPrompt?: string;
  drizzle?: {
    mode?: 'json' | 'timestamp' | 'timestamp_ms' | 'boolean' | 'bigint';
    customType?: string;
  };
  nested?: {
    enabled: true;
    relation: 'has-one' | 'has-many';
  };
  foreignKey?: ForeignKeyRef;
  properties?: Record<string, JsonSchemaProperty>;
  items?: JsonSchemaProperty;
  required?: string[];
}
export interface MigrationConfig {
  schemaPath: string;
  drizzleSchemaPath: string;
  migrationsPath: string;
  databasePath: string;
  drizzleConfigPath: string;
}
export interface ParsedColumn {
  name: string;
  columnType: ColumnType;
  isPrimary: boolean;
  isAutoIncrement: boolean;
  isNullable: boolean;
  isUnique: boolean;
  default?: unknown;
  isForeignKey?: boolean;
  foreignKeyRef?: {
    table: string;
    column: string;
  };
}
export interface ParsedRelation {
  fromTable: string;
  fromColumn: string;
  toTable: string;
  toColumn: string;
  name: string;
}
export interface ParsedTable {
  name: string;
  columns: ParsedColumn[];
  checks?: CheckConstraint[];
}
export interface ParseResult {
  tables: ParsedTable[];
  relations: ParsedRelation[];
  reverseRelations: ParsedReverseRelation[];
  warnings: string[];
}

// Types
export type JsonSchemaDefinition = z.infer<typeof JsonSchemaDefinitionSchema>;

// Functions
export declare function buildDoctorDiagnostics(_: {
  pkg: {
    name: string;
    version: string;
  };
  executable: string;
  node: string;
  platform: string;
  arch: string;
  shell: string;
  packageManager: string;
  osType: string;
  osRelease: string;
  cwd: string;
  imageOcr: DoctorDiagnostics['imageOcr'];
  configPath: string;
  configStoreKeys: string[];
  project: DoctorDiagnostics['project'];
}): DoctorDiagnostics;
export declare function collectDoctorDiagnostics(_?: CollectDoctorDiagnosticsOptions): Promise<DoctorDiagnostics>;
export declare function createMigrationConfig(_: string): MigrationConfig;
export declare function doctorDiagnosticsSeverityRows(_: DoctorDiagnostics): [string, string][];
export declare function doctorDiagnosticsTableRows(_: DoctorDiagnostics): [string, string][];
export declare function formatDoctorDiagnosticsJson(_: DoctorDiagnostics): string;
export declare function generateDrizzleConfig(): string;
export declare function generateDrizzleSchema(_: ParseResult): string;
export declare function parseJsonSchema(_: JsonSchemaDefinition): ParseResult;

// Variables
export declare const JsonSchemaDefinitionSchema: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodObject<{
  $schema: z.ZodOptional<z.ZodString>;
  title: z.ZodString;
  description: z.ZodOptional<z.ZodString>;
  type: z.ZodLiteral<"object">;
  table: z.ZodObject<{
    name: z.ZodString;
    timestamps: z.ZodOptional<z.ZodBoolean>;
    softDelete: z.ZodOptional<z.ZodBoolean>;
  }, "strip", z.ZodTypeAny, {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  }, {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  }>;
  properties: z.ZodRecord<z.ZodString, z.ZodType<JsonSchemaProperty, z.ZodTypeDef, JsonSchemaProperty>>;
  required: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
  examples: z.ZodOptional<z.ZodArray<z.ZodObject<{
    text: z.ZodString;
    output: z.ZodRecord<z.ZodString, z.ZodUnknown>;
  }, "strip", z.ZodTypeAny, {
    text: string;
    output: Record<string, unknown>;
  }, {
    text: string;
    output: Record<string, unknown>;
  }>, "many">>;
}, "strip", z.ZodTypeAny, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}>, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}>, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}>, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}, {
  type: "object";
  table: {
    name: string;
    timestamps?: boolean | undefined;
    softDelete?: boolean | undefined;
  };
  title: string;
  properties: Record<string, JsonSchemaProperty>;
  $schema?: string | undefined;
  description?: string | undefined;
  required?: string[] | undefined;
  examples?: {
    text: string;
    output: Record<string, unknown>;
  }[] | undefined;
}>;